publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "https://landskapeai.github.io"
canonifyurls = true
theme = "academic-group"
title = "Landskape AI"
math = true
copyright = "&copy; Landskape AI, 2020 "
enableRobotsTXT = true

[taxonomies]
category = "categories"
tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Website of research group"
  author = "Landskape AI"
  email = ""
  address = ''
  slogan = "Landskape"
  slogan_icon = "icon-spsbrats_logo"
  slogan_text = "a tiny research group on the edge of theoretical deep learning"
  custom_css = ["biaslab.css"]
  landing_heading = "Natural Artificial Intelligence"
  landing_description = "a tiny research group on the edge of theoretical deep learning"
  positions_available = false

  [params.logo]
    image = "img/logo.png"
    link = "/"

  [[params.sponsors]]
    name = "NCSA"
    link = "https://ncsa.illinois.edu"
    image = "/img/ncsa.png"

  [[params.sponsors]]
    name = "OpenPOWER Foundation"
    link = "https://openpowerfoundation.org/"
    image = "/img/openpower.png"

  # About section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.about]
    title = "About Us"
    subtitle = "Who we are and what we do"
    text = "Some sample text that describes who you are and what you do."
    str_read_more = "Learn more"

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"
  
  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "Blog"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 3
    str_all = "More Projects"

  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.open_projects]
    title = "Open projects"
    subtitle = ""
    count = 3
    str_all = "All open projects"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
    name = "About"
    url = "/#about"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/#projects"
    weight = 2

  [[menu.main]]
    name = "Publications"
    url = "/#publications"
    weight = 3

  [[menu.main]]
    name = "Team"
    url = "/#members"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 5
